# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 02:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0002_auto_20160422_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 22, 2, 17, 10, 484407, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
