# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0004_tag_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vault',
            name='email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vault',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vault',
            name='site_url',
            field=models.URLField(max_length=600),
        ),
        migrations.AlterField(
            model_name='vault',
            name='username',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
