# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0007_auto_20160724_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vault',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vault',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
