# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0008_auto_20160725_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='site_url',
            field=models.TextField(),
        ),
    ]
