# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('password', '0009_auto_20160821_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordFieldHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.TextField()),
                ('iv', models.CharField(max_length=500)),
                ('salt', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Secret',
        ),
        migrations.AddField(
            model_name='recent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vault',
            name='iv',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vault',
            name='salt',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='vault',
            name='tag',
        ),
        migrations.AddField(
            model_name='vault',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='passwordfieldhistory',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password.Vault'),
        ),
    ]
