# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0010_auto_20170129_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent',
            name='accessed_at',
        ),
        migrations.AddField(
            model_name='vault',
            name='audit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='icon',
            field=models.TextField(null=True),
        ),
    ]
