# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0011_auto_20170129_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='recent',
            name='accessed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
