# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0013_auto_20170210_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='iv',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vault',
            name='salt',
            field=models.TextField(),
        ),
    ]
