# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0014_auto_20170305_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordfieldhistory',
            name='vault',
        ),
        migrations.DeleteModel(
            name='PasswordFieldHistory',
        ),
    ]
