# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0015_auto_20170312_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
