# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0017_auto_20170629_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='user',
        ),
    ]
